ALLOWED_COLLIDER_USAGES = [
    ("Main", "Main", "Default usage for colliders"),
    ("Building", "Building", "For static building collisions"),
    ("BuildingFire", "BuildingFire", "For fire collisions on buildings"),
    ("BuildingFireView", "BuildingFireView", "For fire and view collisions on building parts"),
    ("Bush", "Bush", "For foliage collisions"),
    ("Cover", "Cover", "For cover collisions"),
    ("Character", "Character", "For character colliders"),
    ("CharacterAI", "CharacterAI", "For AI character colliders"),
    ("CharNoCollide", "CharNoCollide", "For non-colliding character elements"),
    ("Debris", "Debris", "For debris colliders"),
    ("Door", "Door", "For door collisions"),
    ("DoorFireView", "DoorFireView", "For door collisions with fire and view layers"),
    ("FireGeo", "FireGeo", "For bullet-impact detection on fire geometry"),
    ("Foliage", "Foliage", "For vegetation collisions"),
    ("Interaction", "Interaction", "For interactive colliders"),
    ("ItemFireView", "ItemFireView", "For non-character items that need fire/view collisions"),
    ("Ladder", "Ladder", "For ladder interactions"),
    ("Projectile", "Projectile", "For larger projectiles"),
    ("Prop", "Prop", "For dynamic prop collisions"),
    ("PropView", "PropView", "For dynamic props with view collision"),
    ("PropFireView", "PropFireView", "For dynamic prop collisions with fire/view layers"),
    ("RockFireView", "RockFireView", "For rock collisions with fire/view layers"),
    ("Terrain", "Terrain", "For terrain collisions"),
    ("Tree", "Tree", "For tree collider collisions"),
    ("TreeFireView", "TreeFireView", "For trees with fire/view collision"),
    ("TreePart", "TreePart", "For tree branch colliders"),
    ("Vehicle", "Vehicle", "For vehicle colliders"),
    ("VehicleFire", "VehicleFire", "For vehicles colliding with fire geometry"),
    ("VehicleFireView", "VehicleFireView", "For vehicle collisions with fire and view layers"),
    ("Weapon", "Weapon", "For weapon colliders"),
    ("Wheel", "Wheel", "For vehicle wheel colliders"),
]